# BEGIN_KITTY_THEME
# Dracula
include current-theme.conf
# END_KITTY_THEME

# Font
font_family      JetBrainsMono Nerd Font
bold_font        JetBrainsMono Nerd Font Bold
italic_font      JetBrainsMono Nerd Font Italic
bold_italic_font JetBrainsMono Nerd Font Bold Italic

font_size 12.5
font_size_delta 2

remember_window_size   yes
initial_window_width   640
initial_window_height  400

# Visual bell duration. Flash the screen when a bell occurs for the specified number of
# seconds. Set to zero to disable.
visual_bell_duration 0.0

# Enable/disable the audio bell. Useful in environments that require silence.
enable_audio_bell no

confirm_os_window_close 0
