include current-theme.conf

font_family      AtkynsonMono Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto

font_size 12.5

# Let Hyprland apply the same global transparency used by every other window.
background_opacity 1.0

remember_window_size   yes
initial_window_width   640
initial_window_height  400

visual_bell_duration 0.0

enable_audio_bell no

confirm_os_window_close 0
